version: '3'

services:

  css-server:
    container_name: css-server
    image: foxylion/steam-css:latest
    restart: always
    environment:
      - RCON_PASSWORD=${RCON_PASSWORD}
      - CSS_HOSTNAME=${CSS_HOSTNAME}
      - CSS_PASSWORD=${CSS_PASSWORD}
    ports:
      - 27015:27015/udp
      - 27015:27015
      - 1200:1200
      - 27005:27005/udp
      - 27020:27020/udp
      - 26901:26901/udp
    volumes:
      - /home/centos/lightsail-cs-source/htdocs:/home/steam/htdocs
      - /home/centos/lightsail-cs-source/server.cfg:/home/steam/css/cstrike/cfg/my-server.cfg
      - /home/centos/lightsail-cs-source/admins_simple.ini:/home/steam/css/cstrike/addons/sourcemod/configs/admins_simple.ini
      - /home/centos/lightsail-cs-source/mapcycle.txt:/home/steam/css/cstrike/cfg/mapcycle.txt

  duckdns:
    image: linuxserver/duckdns
    container_name: duckdns
    environment:
      - TZ=${TZ}
      - SUBDOMAINS=${DUCKDNS_SUBDOMAINS}
      - TOKEN=${DUCKDNS_TOKEN}
    volumes:
      - /home/centos/duckdns/config:/config #optional
    restart: unless-stopped

