version: '3'

services:

  css-server:
    container_name: css-server
    build: .
    restart: always
    environment:
      - MAP=${CSS_MAP}
      - MAXPLAYERS=${CSS_MAXPLAYERS}
    ports:
      - 27015:27015/udp
      - 27015:27015
      - 1200:1200
      - 27005:27005/udp
      - 27020:27020/udp
      - 26901:26901/udp
    volumes:
      - /home/centos/lightsail-cs-source/:/data/steam/
      - /home/centos/lightsail-cs-source/server.cfg:/data/steam/css/cstrike/cfg/server.cfg

  duckdns:
    image: linuxserver/duckdns
    container_name: duckdns
    environment:
      - TZ=${TZ}
      - SUBDOMAINS=${DUCKDNS_SUBDOMAINS}
      - TOKEN=${DUCKDNS_TOKEN}
    volumes:
      - /home/centos/duckdns/config:/config #optional
    restart: unless-stopped

